#include "env_mgr.h"

namespace env_mgr {

DEF_ENVIRONMENT_STR(LOG_LEVEL)
DEF_ENVIRONMENT_STR(HOOK_DISABLE_TRACE)
DEF_ENVIRONMENT_STR(LOG_OUTPUT_PATH)
DEF_ENVIRONMENT_STR(TARGET_LIB_FILTER)

}  // namespace env_mgr
