# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            include:
              # - sudo: required
              #   services:
              #     - docker
              #   env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
              #       PLAT=manylinux1_x86_64
              # - sudo: required
              #   services:
              #     - docker
              #   env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
              #       PRE_CMD=linux32
              #       PLAT=manylinux1_i686
              - sudo: required
                services:
                  - docker
                env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
                    PLAT=manylinux2014_x86_64

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    # - name: pull docker0
    #   if: contains(${{ matrix.DOCKER_IMAGE }}, "manylinux1_x86_64") }}
    #   run: |
    #     IMAGE=quay.io/pypa/manylinux1_x86_64
    #     docker pull $IMAGE:latest
    #     docker run --rm -e PLAT=manylinux1_x86_64 -v $(pwd):/io $IMAGE /io/script/build-wheels.sh

    # - name: pull docker1
    #   if: contains(${{ matrix.DOCKER_IMAGE }}, "manylinux1_i686") }}
    #   run: |
    #     IMAGE=quay.io/pypa/manylinux1_i686
    #     docker pull $IMAGE:latest
    #     docker run --rm -e PLAT=manylinux1_i686 -v $(pwd):/io $IMAGE linux32 /io/script/build-wheels.sh   

    - name: pull docker2
      if: contains(${{ matrix.DOCKER_IMAGE }}, "manylinux2014_x86_64") }}
      run: |
        IMAGE=quay.io/pypa/manylinux2014_x86_64
        docker pull $IMAGE:latest
        docker run --rm -e PLAT=manylinux2014_x86_64 -v $(pwd):/io $IMAGE /io/script/publish-build-wheels.sh

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
