# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc-9]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip        

    - name: Set up compiler
      run: |
        if [ "${{ matrix.compiler }}" = "gcc-9" ]; then
          sudo apt-get install -y gcc-9
          sudo apt-get install -y g++-9
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
        fi

    - name: Set up CMake
      run: |
        pip install --upgrade pip
        sudo apt-get install -y cmake

    - name: Build package
      run:  |
        pip install -r requirements.txt
        python setup.py sdist bdist_wheel

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
